### ISSUE TITLE
Can not enable Tooltips on front side

### ISSUE THREAD

**Issue by ChrisNiekler** [kleinerpirat/anki-tooltips#3]
I can not enable it to show tooltips on the front. It will throw the Error below. Seems like it gets the wrong data type.

----
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-02-16 11:40:47

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1840818335\gui\dialogs\model_settings.py", line 48, in accept
    self.callback(
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1840818335\qt\models.py", line 33, in set_settings
    update_model(mw.col.models.get(mid))
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1840818335\utils.py", line 78, in update_model
    mw.col.models.update_dict(model)
  File "anki.models", line 223, in update_dict
  File "anki._backend_generated", line 883, in update_notetype_legacy
  File "anki._backend", line 148, in _run_command
anki.errors.BackendError: JsonError { info: "invalid type: boolean `false`, expected a string at line 1 column 349" }

**Comment by kleinerpirat** [comment]
Thanks for the report! Looking into it. For now, you can also insert the following script to your card template to enable Tooltips:

```html
<script src="_anki-tooltips.js"/></script>
```
and in Style section:

```css
@import url("_anki-tooltips.css");
```

**Comment by ChrisNiekler** [comment]
Yes this works! You can close this Issue whenever you are ready. Thank you
